# Generated by Django 3.2.4 on 2021-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('drugName', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('uniqueId', models.IntegerField()),
                ('usefulCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('m01ab', models.FloatField()),
                ('m01ae', models.FloatField()),
                ('n02ba', models.FloatField()),
                ('n02be', models.FloatField()),
                ('n05b', models.FloatField()),
                ('n05c', models.FloatField()),
                ('r03', models.FloatField()),
                ('r06', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
